/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.test {
	import laya.ui.*;
	import laya.display.*;

	public class TestSceneUI extends Scene {

		override protected function createChildren():void {
			super.createChildren();
			loadScene("test/TestScene");

		}

	}
}