'use strict';var mx={TAB:0,Gj:1,en:2},nx=function(a){yb("MediaRouter.CastStreaming.Start.Success",a,mx)};var ox=db("mr.mirror.cast.LogUploader"),qx=function(a,b,c){px("raw_events.log.gz",a,b,c);return b?"https://crash.corp.google.com/samples?reportid=&q="+encodeURIComponent("UserComments='"+b+"'"):""},px=function(a,b,c,d){if(0==b.size)ox.info("Trying to upload an empty file to Crash"),d&&d(null);else{var e=new FormData;e.append("prod","Cast");e.append("ver",chrome.runtime.getManifest().version);e.append(a,b);c&&e.append("comments",c);Qu("https://clients2.google.com/cr/report",function(a){a=a.target;
var b=null;$u(a)?(b=av(a),ox.info("Upload to Crash succeeded: "+b)):ox.info("Upload to Crash failed. HTTP status: "+a.La());d&&d(b)},"POST",e,void 0,3E4)}};var rx=function(){this.b=0;fj(this)},tx=function(){sx||(sx=new rx);return sx},ux=function(){var a=tx(),b={fraction:.01,autoSubmitTimeLimitMillis:6048E5},c=b.autoSubmitTimeLimitMillis,d=Date.now();return a.b&&c&&d-a.b<c?!1:Math.random()<b.fraction};rx.prototype.Aa=function(){return"mirror.cast.LogUtils"};rx.prototype.gb=function(){return[void 0,{lastAutoSubmitMillis:this.b}]};rx.prototype.fb=function(){var a=dj(this);this.b=a&&a.lastAutoSubmitMillis||0};var sx=null;db("mr.mirror.cast.LogUtils");var vx={Wv:"OFFER",Wr:"ANSWER",xw:"PRESENTATION",Nt:"GET_STATUS",Gx:"STATUS_RESPONSE",Mt:"GET_CAPABILITIES",vs:"CAPABILITIES_RESPONSE",ix:"RPC"};var wx=function(){this.capabilities=this.status=this.b=this.error=this.rpc=this.result=this.type=this.f=this.sessionId=null},zx=function(a){try{if("string"!==typeof a)throw SyntaxError("Cannot parse non-string as JSON");var b;xx(JSON.parse(a),function(a){b=yx(a)},function(){throw Error("non-Object result from JSON parse");});return b}catch(d){var c=d instanceof SyntaxError?"JSON parse error: "+d.message:"Type coercion error: "+d.message}"string"==typeof a?a="a string: "+a:a instanceof ArrayBuffer?
(a=new Uint8Array(a),a="an ArrayBuffer whose base64 is "+btoa(String.fromCharCode.apply(null,a))):a="of invalid data type "+typeof a;throw Error(c+". Input was "+a);},yx=function(a){var b=new wx;null!=a.sessionId&&(b.sessionId=String(a.sessionId));Ax(a.seqNum,function(a){b.f=a},function(){throw Error('"seqNum" must be a number');});if("type"in a){for(var c=String(a.type).toUpperCase(),d=k(Object.keys(vx)),e=d.next();!e.done;e=d.next())if(vx[e.value]==c){b.type=c;break}if(!b.type)throw Error('not a known message "type"');
}"result"in a&&(b.result=String(a.result));if("rpc"in a){if("string"!==typeof a.rpc)throw Error('"rpc" must be a String containing a base64 payload');b.rpc=new Uint8Array([].concat(m(atob(a.rpc))).map(function(a){return a.charCodeAt(0)}))}xx(a.error,function(a){b.error=Bx(a)},function(){throw Error('"error" must be an Object');});xx(a.answer,function(a){b.b=Cx(a)},function(){throw Error('"answer" must be an Object');});xx(a.status,function(a){b.status=Dx(a)},function(){throw Error('"status" must be an Object');
});xx(a.capabilities,function(a){b.capabilities=Ex(a)},function(){throw Error('"capabilities" must be an Object');});return b},xx=function(a,b,c){void 0!==a&&(a instanceof Object?b(a):c())},Ax=function(a,b,c){void 0!==a&&("number"!==typeof a?c():b(a))},Fx=function(a,b,c){void 0!==a&&(a instanceof Array&&a.every(function(a){return"number"===typeof a})?b(a):c())},Gx=function(a,b,c){void 0!==a&&(a instanceof Array?b(a.map(function(a){return String(a)})):c())},Hx=function(){this.j=null;this.b=[];this.f=
[];this.g=this.h=this.l=null},Cx=function(a){var b=new Hx;Ax(a.udpPort,function(a){b.j=a},function(){throw Error('"answer.udpPort" must be a number');});Fx(a.sendIndexes,function(a){b.b=a},function(){throw Error('"answer.sendIndexes" must be an array of numbers');});Fx(a.ssrcs,function(a){b.f=a},function(){throw Error('"answer.ssrcs" must be an array of numbers');});"IV"in a&&(b.l=String(a.IV));"receiverGetStatus"in a&&(b.h="true"==String(a.receiverGetStatus).toLowerCase());"castMode"in a&&(b.g=String(a.castMode));
return b},Ix=function(){this.details=this.description=this.code=null},Bx=function(a){var b=new Ix;Ax(a.code,function(a){b.code=a},function(){throw Error('"error.code" must be a number');});"description"in a&&(b.description=String(a.description));xx(a.details,function(a){b.details=a},function(){throw Error('"error.details" must be an Object');});return b},Jx=function(){this.f=this.b=null},Dx=function(a){var b=new Jx;Ax(a.wifiSnr,function(a){b.b=a},function(){throw Error('"status.wifiSnr" must be a number');
});Fx(a.wifiSpeed,function(a){b.f=a},function(){throw Error('"status.wifiSpeed" must be an array of numbers');});return b},Kx=function(){this.f=this.b=null},Ex=function(a){var b=new Kx;Gx(a.mediaCaps,function(a){b.b=a},function(){throw Error('"capabilities.mediaCaps" must be an array');});if("keySystems"in a){a=a.keySystems;if(!(a instanceof Array))throw Error('"capabilities.keySystems" must be an array');b.f=a.map(function(a){var b;xx(a,function(a){b=Lx(a)},function(){throw Error('"capabilities.keySystems" entries must be *Objects');
});return b})}return b},Mx=function(){this.g=this.o=this.l=this.j=this.C=this.b=this.s=this.f=this.initDataTypes=this.h=null},Lx=function(a){var b=new Mx;"keySystemName"in a&&(b.h=String(a.keySystemName));Gx(a.initDataTypes,function(a){b.initDataTypes=a},function(){throw Error('"capabilities.initDataTypes" must be an array');});Gx(a.codecs,function(a){b.f=a},function(){throw Error('"capabilities.codecs" must be an array');});Gx(a.secureCodecs,function(a){b.s=a},function(){throw Error('"capabilities.secureCodecs" must be an array');
});Gx(a.audioRobustness,function(a){b.b=a},function(){throw Error('"capabilities.audioRobustness" must be an array');});Gx(a.videoRobustness,function(a){b.C=a},function(){throw Error('"capabilities.videoRobustness" must be an array');});"persistentLicenseSessionSupport"in a&&(b.j=String(a.persistentLicenseSessionSupport));"persistentReleaseMessageSessionSupport"in a&&(b.l=String(a.persistentReleaseMessageSessionSupport));"persistentStateSupport"in a&&(b.o=String(a.persistentStateSupport));"distinctiveIdentifierSupport"in
a&&(b.g=String(a.distinctiveIdentifierSupport));return b};var Nx=function(a){this.m=db("mr.mirror.cast.MessageDispatcher");this.h=a;this.b=null;this.f=new Map;this.g=0},Ox=function(a,b,c){if(a.f.has(b))throw Error("Attempt to multiple-subscribe to the same response type: "+b);a.f.set(b,c);a.g=0;kb(a.m,"Added subscriber for "+b+"-type messages.");a.b||(a.b=kw(a.h),a.b.onMessage=a.j.bind(a))},Px=function(a,b){a.f.delete(b)&&kb(a.m,function(){return"Removed subscriber of "+b+"-type messages."});0==a.f.size&&a.b&&(a.b.Oa(),a.b=null)};
Nx.prototype.sendMessage=function(a){return this.b?"RPC"==a.type?this.b.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.remoting"}):this.b.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.webrtc"}):Promise.reject(Error("Require at least one subscriber before sending messages."))};
var Qx=function(a,b,c,d,e){var f=null,h=function(){Px(a,c);null!=f&&(clearTimeout(f),f=null)};try{Ox(a,c,function(a){e(a)&&h()})}catch(l){e(null,l);return}f=setTimeout(function(){h();e(null,Error("timeout"))},d);a.sendMessage(b).catch(function(a){h();e(null,a)})};
Nx.prototype.j=function(a){if(a&&"string"===typeof a.namespace_&&a.namespace_.startsWith("urn:x-cast:com.google.cast.")){do{var b=void 0;try{b=zx(a.data)}catch(d){b=d.message;break}if(b.type){var c=this.f.get(b.type);if(c)try{c(b);return}catch(d){b="Error thrown during delivery. Response was: "+(JSON.stringify(b)+". Error from subscriber callback ")+("was: "+d.message+".")}else b="Message was ignored: "+JSON.stringify(b)}else b="Message did not include response type: "+JSON.stringify(b)}while(0);
10>this.g?this.m.F(b):kb(this.m,b);++this.g}};var Rx=function(){this.b=Promise.resolve(1)},Tx=function(a,b,c){return Sx(a,function(a){return a==b},c)},Ux=function(a,b){var c=[3,4];return Sx(a,function(a){return-1!=c.indexOf(a)},b)},Vx=function(a,b){a.b=a.b.catch(function(){return 1});return Sx(a,function(){return!0},b)},Sx=function(a,b,c){var d,e,f=new Promise(function(a,b){d=a;e=b});a.b=a.b.then(function(a){if(!b(a))return e(Error("Operation requires a different starting checkpoint than "+a)),Promise.resolve(a);var f=new Wx(a);try{var h=c(f)}catch(u){h=
Promise.reject(u)}return h.then(function(a){return d(a)},function(a){return e(a)}).then(function(){if(null===f.b)throw Error("A prior operation that started at "+(a+" did not complete."));return f.b})},function(a){e(a);throw a;});return f},Wx=function(a){this.f=a;this.b=null},Xx=function(a,b){a.b="number"===typeof b?b:a.f};var Yx=chrome.cast.streaming,$x=function(a,b,c,d,e){this.H=a.sessionId;this.C=a.Df;this.W=a.Qd;this.g=b;this.G=c;this.D=d;this.M=Zx(e,"onAnswer",this.C);this.N=Zx(e,"onSessionStop",this.C);this.m=db("mr.mirror.cast.StreamingLaunchWorkflow");this.A=new Rx;this.o=this.w=this.s=this.f=this.b=this.l=this.j=this.h=null};
$x.prototype.start=function(a,b,c){var d=this;if(!a&&!b)return Promise.reject(Error("No tracks to stream"));var e=a instanceof ay,f=b instanceof ay;(e&&b&&!f||f&&a&&!e)&&Db("Mixing remoting and non-remoting tracks");return Tx(this.A,1,function(e){d.h=a;d.j=b;d.l=c;d.m.info(function(){return"Launching streaming for "+by(d)+" "+("to a "+d.W+".")});return cy(d).then(d.B.bind(d)).then(function(a){return dy(d,a).then(function(b){d.M();var c=ey(d,b,a);d.b=fy(d,d.b,c);d.f=fy(d,d.f,c);if(!d.b&&!d.f)throw Error("Receiver did not select any offers from: "+
JSON.stringify(a));d.w=!!b.h;d.o=function(a,b){a==d.b?d.l.Ee("Audio stream (id="+a+") error: "+b):a==d.f&&d.l.Ee("Video stream (id="+a+") error: "+b)};Yx.rtpStream.onError.addListener(d.o);return gy(d,b,c)})}).then(function(){d.m.info(function(){return"Launched streaming for "+by(d)});d.l.Tf(d);Xx(e,2);return{xo:d.b,vr:d.f}})})};
$x.prototype.stop=function(){var a=this;return Vx(this.A,function(b){if(!a.h&&!a.j)return Xx(b,1),Promise.resolve();a.m.info(function(){return"Stopping streaming for "+by(a)+"."});a.o&&(Yx.rtpStream.onError.removeListener(a.o),a.o=null);if(a.l){var c=a.l.Dg();a.l=null}else c=Promise.resolve();return c.then(function(){a.b&&(Yx.rtpStream.stop(a.b),Yx.rtpStream.destroy(a.b),a.b=null);a.f&&(Yx.rtpStream.stop(a.f),Yx.rtpStream.destroy(a.f),a.f=null);a.s&&(Yx.udpTransport.destroy(a.s),a.s=null);a.N();a.m.info(function(){return"Stopped streaming for "+
by(a)+"."});a.h=null;a.j=null;Xx(b,1)})})};
var hy=function(a,b){var c=JSON.stringify(b);return Promise.all([a.b&&new Promise(function(b){return Yx.rtpStream.getRawEvents(a.b,c,b)}),a.f&&new Promise(function(b){return Yx.rtpStream.getRawEvents(a.f,c,b)})]).catch(function(b){a.m.error("Unexpected error when calling getRawEvents()",b);return[]}).then(function(a){return new Blob(a.filter(function(a){return!!a}),{type:"application/gzip"})})},iy=function(a){return Promise.all([a.b&&new Promise(function(b){return Yx.rtpStream.getStats(a.b,b)}),a.f&&
new Promise(function(b){return Yx.rtpStream.getStats(a.f,b)})]).catch(function(b){a.m.error("Unexpected error when calling getStats()",b);return[]}).then(function(a){return Object.assign.apply(Object,[{}].concat(m(a.filter(function(a){return!!a}))))})},by=function(a){if(a.h&&a.j)var b="audio+video ";else if(a.h)b="audio-only ";else if(a.j)b="video-only ";else return"stopped";return a.h instanceof ay||a.j instanceof ay?b+"remoting":b+"streaming"},cy=function(a){return new Promise(function(b){var c=
function(c,e,f){c&&!a.h&&(Yx.rtpStream.destroy(c),c=null);e&&!a.j&&(Yx.rtpStream.destroy(e),e=null);a.m.info(function(){return"Created Cast Streaming session: audioStreamId="+c+", videoStreamId="+e+"."});a.b=c;a.f=e;a.s=f;b()};a.h instanceof ay||a.j instanceof ay?Yx.session.create(null,null,c):Yx.session.create(a.h,a.j,c)})};
$x.prototype.B=function(){for(var a=ch(),b=ch(),c=[],d=k([this.b,this.f]),e=d.next();!e.done;e=d.next())if(e=e.value)for(var f=e==this.b,h=f?127:96,l=f?Math.floor(499999*Math.random())+1:Math.floor(499999*Math.random())+500001,t=f?48E3:9E4,u=k(Yx.rtpStream.getSupportedParams(e)),A=u.next();!A.done;A=u.next())A=A.value,A.payload.payloadType=h,A.payload.maxLatency=this.g.maxLatencyMillis,A.payload.minLatency=this.g.minLatencyMillis,A.payload.animatedLatency=this.g.animatedLatencyMillis,A.payload.ssrc=
l,A.payload.clockRate=t,A.payload.aesKey=a,A.payload.aesIvMask=b,f?(A.payload.channels=2,A.payload.maxBitrate=this.g.audioBitrate,A.payload.maxFrameRate=100):(A.payload.minBitrate=this.g.minVideoBitrate,A.payload.maxBitrate=this.g.maxVideoBitrate,A.payload.maxFrameRate=this.g.maxFrameRate),c.push(new jy(e,A));return c};
var fy=function(a,b,c){b&&!c.some(function(a){return a.Gf==b})&&(a.m.F("Destroying RTP stream not selected by the receiver: id="+b),Yx.rtpStream.destroy(b),b=null);return b},dy=function(a,b){return new Promise(function(c,d){for(var e=[],f=0;f<b.length;++f){var h=b[f].params,l={index:f,codecName:h.payload.codecName.toLowerCase(),rtpProfile:"cast",rtpPayloadType:h.payload.payloadType,ssrc:h.payload.ssrc,targetDelay:h.payload.animatedLatency,aesKey:h.payload.aesKey,aesIvMask:h.payload.aesIvMask,timeBase:"1/"+
h.payload.clockRate,receiverRtcpEventLog:a.g.enableLogging,rtpExtensions:["adaptive_playout_delay"]};a.g.dscpEnabled&&(l.receiverRtcpDscp=46);127==h.payload.payloadType?Object.assign(l,{type:"audio_source",bitRate:0<h.payload.maxBitrate?1E3*h.payload.maxBitrate:60*h.payload.maxFrameRate+h.payload.clockRate*h.payload.channels,sampleRate:h.payload.clockRate,channels:h.payload.channels}):Object.assign(l,{type:"video_source",renderMode:"video",maxFrameRate:Math.round(1E3*h.payload.maxFrameRate)+"/1000",
maxBitRate:1E3*h.payload.maxBitrate,resolutions:[{width:a.g.maxWidth,height:a.g.maxHeight}]});e.push(l)}var t=a.h instanceof ay||a.j instanceof ay?"remoting":"mirroring",u={type:"OFFER",sessionId:a.H,seqNum:uk(a.G),offer:{castMode:t,receiverGetStatus:!0,supportedStreams:e}};a.m.info(function(){return"Sending OFFER message: "+JSON.stringify(u)});Qx(a.D,u,"ANSWER",1E4,function(b,e){if(null==b)d(e);else if("ok"==b.result&&b.b){if(b.f!=u.seqNum)return a.m.F("Ignoring ANSWER for OFFER with different seqNum: "+
JSON.stringify(b)),!1;((e=b.b.g)&&e!=t||!e&&"mirroring"!=t)&&a.m.error("Expected receiver to ANSWER with castMode="+t+", but got: "+e);kb(a.m,function(){return"Received ANSWER: "+JSON.stringify(b)});c(b.b)}else d(Error("Non-OK ANSWER received: "+JSON.stringify(b)));return!0})})},ey=function(a,b,c){if(b.b.length!=b.f.length)return a.m.error("sendIndexes.length != ssrcs.length in ANSWER: "+JSON.stringify(b)),[];for(var d=[],e={},f=0;f<b.b.length;e={candidate:e.candidate},++f){var h=b.b[f];if(0>h||h>=
c.length)return a.m.error("Receiver selected invalid index ("+h+" < "+c.length+") in ANSWER: "+JSON.stringify(b)),[];e.candidate=c[h];if(d.some(function(a){return function(b){return b.Gf==a.candidate.Gf}}(e)))return a.m.error("Receiver selected same RTP stream twice in ANSWER: "+JSON.stringify(b)),[];e.candidate.params.payload.feedbackSsrc=b.f[h];if(d.some(function(a){return function(b){return b.params.payload.feedbackSsrc==a.candidate.params.payload.feedbackSsrc}}(e)))return a.m.error("Receiver provided same SSRC for two different RTP streams in ANSWER: "+
JSON.stringify(b)),[];d.push(e.candidate)}return d},gy=function(a,b,c){var d=null,e=function(){d&&(Yx.rtpStream.onStarted.removeListener(d),d=null)};return(new Promise(function(e,h){var f=b.j||2344;a.m.info(function(){return"Starting RTP streams to receiver at "+(a.C+":"+f)+(" for selected offers: "+JSON.stringify(c))});var t=a.s||-1;a.g.dscpEnabled&&(a.m.info("Enabled DSCP in sender."),Yx.udpTransport.setOptions(t,{DSCP:!0}));Yx.udpTransport.setDestination(t,{address:a.C,port:f});var u=new Set(c.map(function(a){return a.Gf}));
d=function(a){u.delete(a);0==u.size&&e()};Yx.rtpStream.onStarted.addListener(d);t=k(c);for(var A=t.next();!A.done;A=t.next())A=A.value,Yx.rtpStream.toggleLogging(A.Gf,a.g.enableLogging),Yx.rtpStream.start(A.Gf,A.params);setTimeout(function(){h(Error("Timeout: RTP streams failed to start."))},1E4)})).then(e).catch(function(a){e();throw a;})},Zx=function(a,b,c){var d=this;return a&&b in a?function(){try{a[b](c)}catch(e){d.m.error("Error from testHooks."+b,e)}}:function(){}},jy=function(a,b){this.Gf=
a;this.params=b},ay=function(){};var my=function(a,b,c,d,e,f){this.o=a;this.D=ky(b,this.o.ib);this.G=new $x(this.o.ib,c,d,e,f);this.w=e;this.j=new Rx;this.g=new ly;this.A=new mojo.Binding(mojo.MirrorServiceRemoter,this,null);this.m=db("mr.mirror.cast.MediaRemoter");this.C=this.b=this.l=this.h=this.B=null;this.f=!0;this.s=this.H.bind(this)};
my.prototype.Ya=function(a,b){var c=this;return Tx(this.j,1,function(d){c.B=a;c.h=b;var e=c.A.createInterfacePtrAndBind();c.A.setConnectionErrorHandler(function(){c.m.info("Remoter mojo pipe connection error.");ny(c)});c.b=new mojo.MirrorServiceRemotingSourcePtr;var f=vg(c.o.mediaSource||"");if(!f)throw Error("Failed to parse tab ID from source:\n          "+c.o.mediaSource);c.m.info("Connecting remoter to browser: tabId="+f);(bg.get("mr.ProviderManager")||null).onMediaRemoterCreated(f,e,mojo.makeRequest(c.b));
c.b.ptr.setConnectionErrorHandler(function(){c.m.info("RemotingSource mojo pipe connection error.");ny(c)});return oy(c).then(function(){if(c.f)c.b.onSinkAvailable(c.D);Xx(d,2)})})};
var ny=function(a){return Vx(a.j,function(b){a.b&&(a.b.ptr.reset(),a.b=null);var c=a.l;a.l=null;a.h=null;a.B=null;a.A.close();chrome.settingsPrivate.onPrefsChanged.hasListener(a.s)&&chrome.settingsPrivate.onPrefsChanged.removeListener(a.s);return new Promise(function(d){window.setTimeout(function(){py(a).then(function(){Xx(b,1);d();c&&c()})},250)})})};g=my.prototype;g.Xq=function(a){qy(this.g,a)};g.Tf=function(a){this.h&&this.h.Tf(a)};g.Dg=function(){return this.h?this.h.Dg():Promise.resolve()};
g.Ee=function(a,b){this.m.error("Error during streaming: "+a,b);if(this.b)this.b.onError();ny(this)};
g.start=function(){var a=this,b=!1;this.m.info(function(){b=!0;return"Starting next media remoting session."});b&&ry(this.g,function(b){return a.m.info(b)});sy(this.g);Tx(this.j,2,function(b){return(0,a.B)().then(function(c){a.l=c;Ox(a.w,"RPC",function(b){if(b.rpc){var c=a.g;b=b.rpc;c.l&&(++c.o,c.f+=b.length,c.l(b))}});Xx(b,3)}).catch(function(c){return py(a).then(function(){Xx(b);throw c;})})}).then(function(){a.m.info("Remoting started successfully.")}).catch(function(b){a.m.error("Failed to start remoting",b);
a.b.onError()})};g.nr=function(a,b){var c=this;return Tx(this.j,3,function(d){return c.G.start(a?new ay:null,b?new ay:null,c).then(function(a){ty(c.g,function(a){return c.w.sendMessage(a)},function(a){c.b.onMessageFromSink(a)});Xx(d,4);return{audio_stream_id:a.xo||-1,video_stream_id:a.vr||-1}}).catch(function(a){return py(c).then(function(){Xx(d);throw a;})})}).catch(function(a){c.m.error("Failed to start remoting streams",a);ny(c);return{audio_stream_id:-1,video_stream_id:-1}})};
g.stop=function(a){var b=this;Ux(this.j,function(c){b.b.onStopped(a);return py(b).then(function(){b.m.info("Remoting stopped.");Xx(c,5);(0,b.l)().then(function(){return Tx(b.j,5,function(a){if(b.b&&b.f)b.b.onSinkAvailable(b.D);Xx(a,2);return Promise.resolve()})}).catch(function(a){throw a;});b.l=null})}).catch(function(a){b.m.error("Failed to stop remoting: ",a);ny(b)})};
g.No=function(){null===this.C&&(this.C=xe(this.o.ib.Df).then(function(a){return a.f||!1}));return this.C.then(function(a){return{rate:(a?1E7:5E6)/8}})};
var py=function(a){return a.G.stop().then(function(){Px(a.w,"RPC");uy(a.g);vy(a.g)})},oy=function(a){return new Promise(function(b){chrome.settingsPrivate.getPref("media_router.media_remoting.enabled",function(c){chrome.runtime.lastError?a.m.error("Encountered error getting media remoting pref: "+JSON.stringify(chrome.runtime.lastError)):c.type!=chrome.settingsPrivate.PrefType.BOOLEAN?a.m.error("Pref value not a boolean: "+JSON.stringify(c)):(a.f=!!c.value,a.m.info("Initializing mediaRemotingEnabled_ with value read from pref: "+
a.f));chrome.settingsPrivate.onPrefsChanged.hasListener(a.s)||chrome.settingsPrivate.onPrefsChanged.addListener(a.s);b()})})};
my.prototype.H=function(a){if(this.b){a=k(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value,"media_router.media_remoting.enabled"==b.key){if(b.type!=chrome.settingsPrivate.PrefType.BOOLEAN){this.m.error("Pref value not a boolean: "+JSON.stringify(b));break}a=!!b.value;if(this.f==a)break;this.f=a;this.m.info("mediaRemotingEnabled_ changed to: "+this.f);if(this.f)this.b.onSinkAvailable(this.D);else this.b.onStopped(mojo.RemotingStopReason.USER_DISABLED);break}}};
var ky=function(a,b){var c=this,d=new mojo.RemotingSinkMetadata;d.features=[];d.friendly_name=b.mr||"";d.audio_capabilities=[];d.video_capabilities=[];var e=mojo.RemotingSinkAudioCapability,f=mojo.RemotingSinkVideoCapability,h=d.audio_capabilities,l=d.video_capabilities,t=b.Qd||"";(a.b||[]).forEach(function(a){switch(a){case "audio":h.push(e.CODEC_BASELINE_SET);break;case "aac":h.push(e.CODEC_AAC);break;case "opus":h.push(e.CODEC_OPUS);break;case "video":l.push(f.CODEC_BASELINE_SET);break;case "4k":l.push(f.SUPPORT_4K);
break;case "h264":l.push(f.CODEC_H264);break;case "vp8":l.push(f.CODEC_VP8);break;case "vp9":t.startsWith("Chromecast Ultra")&&l.push(f.CODEC_VP9);break;case "hevc":t.startsWith("Chromecast Ultra")&&l.push(f.CODEC_HEVC);break;default:c.m.info("Unknown mediaCap name: "+a)}});b.Qd&&"Chromecast Ultra"==b.Qd&&l.push(f.SUPPORT_4K);return d};my.prototype.estimateTransmissionCapacity=my.prototype.No;my.prototype.stop=my.prototype.stop;my.prototype.startDataStreams=my.prototype.nr;my.prototype.start=my.prototype.start;
my.prototype.sendMessageToSink=my.prototype.Xq;
var ly=function(){this.l=this.j=this.b=null;this.C=this.f=this.o=this.g=this.s=0;this.h=null},sy=function(a){a.b=[];wy(a,performance.now())},ty=function(a,b,c){a.j=b;a.l=c;a.b?(b=a.b,a.b=null,b.forEach(function(b){return qy(a,b.data).then(b.Zq,b.Wl)})):wy(a,performance.now())},uy=function(a){if(a.b){var b=Error("Stop before delivering pending message");a.b.forEach(function(a){return a.Wl(b)});a.b=null}a.j=null;a.l=null},qy=function(a,b){if(a.j){var c=btoa(String.fromCharCode.apply(null,b));++a.s;
a.g+=b.length;return a.j({type:"RPC",rpc:c})}return a.b?new Promise(function(c,e){a.b.push({data:b,Zq:c,Wl:e})}):Promise.reject(Error("RPC pipe not started"))},ry=function(a,b){vy(a);a.h=setInterval(function(){if(a.b)var c=a.b.length+" messages are waiting to send.";else{c=performance.now();var d=(c-a.C)/1E3;d="Over the past "+d.toFixed(1)+" seconds, sent "+(a.s+" messages ("+Math.round(a.g/d)+" bytes/sec) and ")+("received "+a.o+" messages ("+Math.round(a.f/d)+" ")+"bytes/sec).";wy(a,c);c=d}b(c)},
3E4)},vy=function(a){null!=a.h&&(clearInterval(a.h),a.h=null)},wy=function(a,b){a.s=0;a.g=0;a.o=0;a.f=0;a.C=b};var xy=function(a){return a&&a.getAudioTracks()&&0<a.getAudioTracks().length?a.getAudioTracks()[0]:null},yy=function(a){return a&&a.getVideoTracks()&&0<a.getVideoTracks().length?a.getVideoTracks()[0]:null};var zy=function(a,b,c,d,e){this.g=new $x(a,b,c,d,void 0===e?null:e);this.m=db("mr.mirror.cast.MediaStreamer");this.j=new Rx;this.h=this.f=this.b=this.l=null};zy.prototype.start=function(a,b){var c=this;return Tx(this.j,1,function(d){c.l=a;c.b=xy(a);c.b&&"ended"==c.b.readyState&&(c.b=null);c.f=yy(a);c.f&&"ended"==c.f.readyState&&(c.f=null);if(!c.b&&!c.f)return Xx(d),Promise.reject(Error("No MediaStream tracks to stream."));c.h=b;return c.g.start(c.b,c.f,c.h).then(function(){return Xx(d,2)})})};
zy.prototype.stop=function(){var a=this;return Vx(this.j,function(b){return a.g.stop().then(function(){a.b=null;a.f=null;a.l=null;a.h=null;Xx(b,1)})})};var Ay=function(a){return Tx(a.j,2,function(b){a.m.info("Suspending media streaming...");return a.g.stop().then(function(){a.m.info("Suspended media streaming.");Xx(b,3)})})};
zy.prototype.resume=function(){var a=this;return Tx(this.j,3,function(b){a.b&&"ended"==a.b.readyState&&(a.b=null);a.f&&"ended"==a.f.readyState&&(a.f=null);if(!a.b&&!a.f)return Promise.reject(Error("Cannot resume: All tracks have ended."));a.m.info("Resuming media streaming...");return a.g.start(a.b,a.f,a.h).then(function(){a.m.info("Resumed media streaming.");Xx(b,2)})})};var By=function(a,b,c){this.j=a;this.h=b;this.g=c;this.m=db("mr.mirror.cast.WifiStatusMonitor");this.b=null;this.f=[]};By.prototype.start=function(){var a=this;null==this.b&&(kb(this.m,"Starting Wifi Status Monitoring."),this.f=[],Ox(this.g,"STATUS_RESPONSE",function(b){return Cy(a,b)}),this.b=setInterval(function(){return Dy(a)},12E4),Dy(this))};By.prototype.stop=function(){null!=this.b&&(kb(this.m,"Stopping Wifi Status Monitoring."),clearInterval(this.b),this.b=null,Px(this.g,"STATUS_RESPONSE"))};
var Cy=function(a,b){if(null!=a.b)if(b.status){var c={};null!=b.status.b&&(c.wifiSnr=b.status.b);null!=b.status.f&&(c.wifiSpeed=b.status.f[3]);0==Object.keys(c).length?a.m.F(function(){return"No status fields populated in response: "+JSON.stringify(b)}):(c.timestamp=Date.now(),30==a.f.length&&a.f.shift(),a.f.push(c),a.m.info(function(){return"Current Wifi status: "+JSON.stringify(c)}))}else a.m.F(function(){return"Ignoring response without status: "+JSON.stringify(b)})},Dy=function(a){a.g.sendMessage({type:"GET_STATUS",
sessionId:a.j,seqNum:uk(a.h),get_status:["wifiSnr","wifiSpeed"]})};var Ey=function(a,b,c,d){this.D=b.Df;this.o={extVersion:chrome.runtime.getManifest().version,extChannel:"public",mirrorSettings:Kg(a),sender:navigator.userAgent||"UNKNOWN",receiverProductName:b.Qd};this.B=c;this.w=d;this.h=this.f=this.s=this.l=this.j=this.C=this.g=null;this.b=[]};Ey.prototype.Tf=function(a){null!=this.f&&clearInterval(this.f);this.g=a;this.C=Date.now();this.f=setInterval(this.A.bind(this,a),9E5)};
Ey.prototype.Dg=function(){null!=this.f&&(clearInterval(this.f),this.f=null);if(null!=this.g){var a=this.A(this.g);this.g=null;return a}return Promise.resolve()};Ey.prototype.Ee=function(a,b){null==this.j&&(this.j=Date.now(),"function"===typeof a?this.l=a():"string"===typeof a&&(this.l=a),b&&"string"===typeof b.stack&&(this.s=b.stack))};
var Gy=function(a,b){return(null==a.g?Promise.resolve():a.A(a.g)).then(function(){var c=b.map(function(b){b=Fy(a,b);var c=b.map(function(a){return a.events}).filter(function(a){return null!=a}),d=["["];b.map(function(a){return a.Ff}).forEach(function(a,b){0<b&&d.push(",");d.push(a)});d.push("]");return{events:new Blob(c,{type:"application/gzip"}),Ff:new Blob(d,{type:"application/json"})}});a.b=[];return c})};
Ey.prototype.A=function(a){var b=this;if(null!=this.h)return this.h;var c=xe(this.D).then(function(c){c={receiverVersion:c.b,receiverConnected:c.h,receiverOnEthernet:c.f,receiverHasUpdatePending:c.g,receiverUptimeSeconds:c.j};Object.assign(c,b.o);var d=Date.now();Object.assign(c,{startTime:b.C,endTime:d,activity:by(a),receiverWifiStatus:Array.from(b.w.f)});b.C=d;null!=b.j&&(Object.assign(c,{streamingErrorTime:b.j,streamingErrorMessage:b.l,streamingErrorCause:b.s}),b.j=null,b.l=null,b.s=null);return c});
return(this.h=Promise.all([c.then(function(b){return hy(a,b)}),c,iy(a)]).then(function(a){var c=k(a);a=c.next().value;var d=c.next().value;c=c.next().value;b.b.push({events:a,Ff:new Blob([JSON.stringify(Object.assign({tags:d},c))],{type:"application/json"})});b.b=Fy(b,b.B);b.h=null}))||Promise.resolve()};
var Fy=function(a,b){b-=2;for(var c=[],d=a.b.length-1;0<=d;--d){b-=a.b[d].Ff.size+1;if(0>b)break;c.push({events:null,Ff:a.b[d].Ff});if(null!=a.b[d].events){var e=a.b[d].events.size;b>=e&&(c[c.length-1].events=a.b[d].events,b-=e)}}return c.reverse()};var Hy=db("mr.NetworkUtils"),Iy=function(a,b){return Nf?new Promise(function(c,d){chrome.networkingPrivate.setWifiTDLSEnabledState(a,b,function(a){chrome.runtime.lastError?(Hy.F("Unable to set TDLS state: state = "+b+", error = "+chrome.runtime.lastError.message),d("Unable to set TDLS state to "+b+".")):(Hy.info("TDLS state changed: state = "+b+", status = "+a),c(a))})}):Promise.reject("TDLS feature not enabled.")};var Jy=function(a,b,c,d){d=void 0===d?null:d;Hg.call(this,b);var e=b.ib;this.A=e.sessionId;this.G=e.Df;this.B=a;this.W=d;this.m=db("mr.mirror.cast.Session");this.s=new Rx;this.o=new tk("mirror.cast.SeqNumGenerator");this.l=new Nx(b.id);this.j=new zy(e,this.B,this.o,this.l,this.W);this.h=null;this.b=new Ey(a,e,c,new By(this.A,this.o,this.l));this.f=!1;this.w=null};n(Jy,Hg);g=Jy.prototype;
g.start=function(a){var b=this;return Tx(this.s,1,function(c){var d=new ob("MediaRouter.CastStreaming.Session.Launch");return Ky(b).then(function(c){b.f=c;return b.j.start(a,b)}).then(function(){if(b.j.g.w){var a=b.b;a.o.tdlsIsOn=b.f;a.w.start();Ly(b)}else b.b.o.tdlsIsOn=b.f;d.b();b.w=new ub("MediaRouter.CastStreaming.Session.Length");Xx(c,2);return b})})};
g.stop=function(){var a=this;return Vx(this.s,function(b){a.w&&(a.w.b(),a.w=null);a.b.w.stop();return a.j.stop().then(function(){return a.h?ny(a.h):Promise.resolve()}).then(function(){a.h=null;return a.f?My(a):Promise.resolve()}).then(function(){a.f=!1;Xx(b,4)})})};g.Ul=function(){var a={sessionId:this.A,seqNum:uk(this.o),type:"PRESENTATION",icons:[],title:Fg(this.cc)};this.m.info("Sending session metadata update to receiver: "+this.A);this.l.sendMessage(a)};g.Tf=function(a){this.b.Tf(a)};g.Dg=function(){return this.b.Dg()};
g.Ee=function(a,b){this.b.Ee(a,b);this.m.error(a,b);this.stop()};
var Ny=function(a,b){return Gy(a.b,b)},Ky=function(a){return a.B.useTdls?Iy(a.G,!0).then(function(b){if("Connected"==b)return a.m.info("Successfully enabled TDLS."),!0;a.m.F("Did not enable TDLS: result="+b);return!1}).catch(function(b){a.m.F("Error while calling enableTDLS()",b);return!1}):Promise.resolve(!1)},My=function(a){return Iy(a.G,!1).catch(function(b){return a.m.error("Error while turning TDLS back off",b)})},Ly=function(a){Oy(a).then(function(b){(b.b||[]).includes("video")?Py(a,b):a.m.F(function(){return"Receiver incapable of Media Remoting: "+
JSON.stringify(b)})}).catch(function(b){a.m.F("None/Invalid capabilites response. Media Remoting disabled.",b)})},Oy=function(a){return new Promise(function(b,c){var d={type:"GET_CAPABILITIES",sessionId:a.A,seqNum:uk(a.o)};a.m.info(function(){return"Sending GET_CAPABILITIES message: "+JSON.stringify(d)});Qx(a.l,d,"CAPABILITIES_RESPONSE",3E4,function(e,f){if(null==e)return c(f),!0;if("ok"!=e.result||!e.capabilities)return c(Error("Bad response: "+JSON.stringify(e))),!0;if(e.f!=d.seqNum)return a.m.info(function(){return"Ignoring CAPABILITIES_RESPONSE with different seqNum: "+
JSON.stringify(e)}),!1;kb(a.m,function(){return"Received CAPABILITIES_RESPONSE: "+JSON.stringify(e)});b(e.capabilities);return!0})})},Py=function(a,b){Tx(a.s,2,function(c){var d=a.g.ib.Qd||"<UNKNOWN>";if(!d.startsWith("Chromecast")&&!d.startsWith("Eureka Dongle"))return a.m.F("HACK: Media Remoting disabled because the receiver model--"+('"'+d+'" according to discovery--is not a Chromecast.')),Xx(c),Promise.resolve();a.h=new my(a.g,b,a.B,a.o,a.l,a.W);return a.h.Ya(a.M.bind(a),a).catch(function(b){a.m.error("Media Remoting start failed: "+
b.message,b)}).then(function(){return Xx(c)})})};Jy.prototype.M=function(){var a=this;return Tx(this.s,2,function(b){return new Promise(function(c,d){Ay(a.j).then(function(){Xx(b,3);a.H=!0;Bg(a);c(a.N.bind(a))}).catch(function(b){a.Ee("Failed to suspend MediaStreamer before starting remoting",b);d(b)})})})};
Jy.prototype.N=function(){var a=this;return Tx(this.s,3,function(b){return new Promise(function(c,d){a.j.resume().then(function(){Xx(b,2);a.H=!1;Bg(a);c()}).catch(function(b){a.Ee("Failed resume MediaStreamer after ending remoting mode",b);d(b)})})})};var Qy=function(){wg.call(this,"cast_streaming");this.j=this.s=this.D=this.B=this.h=null;this.H=this.G="";this.W=this.o=!1;this.N=this.Rb.bind(this);this.A=null};n(Qy,wg);g=Qy.prototype;g.Uf=function(a){this.o=a||!1;this.W=!0};g.getName=function(){return"cast_streaming"};
g.Ti=function(a,b,c,d,e){var f=this;if(!this.o)return wg.prototype.Ti.call(this,a,b,c,d,e);this.L.info("Start mirroring on route "+a.id);if(!this.W)return Gf(Error("Not initialized"));var h=new Promise(function(h,t){f.l().then(function(){if(rg(b)&&c.shouldCaptureVideo)return(new Promise(function(b){chrome.tabs.get(a.ib.tabId||-1,b)})).then(function(a){return Zf(a).then(function(a){f.H=a})})}).then(function(){return e?e(a).b:a}).then(function(a){f.B=new mojo.Binding(mojo.MirroringSessionObserver,f,
null);f.D=new mojo.Binding(mojo.MirroringCastMessageChannel,f,null);f.j=kw(a.id);f.j.onMessage=f.Op.bind(f);var e=f.B.createInterfacePtrAndBind(),l=f.D.createInterfacePtrAndBind(),t=Ry(a,c);f.h=new mojo.MirroringServiceHostPtr;var u=a.ib.tabId||-1;qg(b)?f.g.getMirroringServiceHostForTab(u,mojo.makeRequest(f.h)):rg(b)?f.g.getMirroringServiceHostForDesktop(u,f.H,mojo.makeRequest(f.h)):tg(b)?(u=new mojo.Url,u.url=b,f.g.getMirroringServiceHostForOffscreenTab(u,d||"",mojo.makeRequest(f.h))):f.h=null;if(!f.h)throw new Kf("Error to get mirroring service host");
f.s=new mojo.MirroringCastMessageChannelPtr;f.h.start(t,e,l,mojo.makeRequest(f.s));f.A=new Hg(a);e=f.g.vi.bind(f.g);f.A.D=e;qg(b)&&!chrome.tabs.onUpdated.hasListener(f.N)&&chrome.tabs.onUpdated.addListener(f.N);(qg(b)||tg(b))&&Ag(f.A,a.ib.tabId);h(a)}).catch(function(a){f.L.info("Mirroring launch error: "+a);t(a)})});return Hf(h)};g.Wg=function(a,b){return new Jy(a,b,20969472,null)};g.wg=function(){nx(0)};g.tg=function(){nx(1)};g.Ch=function(){nx(2)};g.ug=function(){xb("MediaRouter.CastStreaming.Session.End")};
g.Bh=function(a){yb("MediaRouter.CastStreaming.Start.Failure",a,Jf)};g.vg=function(){xb("MediaRouter.CastStreaming.Stream.End")};
g.bi=function(a){var b=this;return this.o?Promise.resolve():(new Promise(function(a){return chrome.metricsPrivate.getIsCrashReportingEnabled(a)})).then(function(c){var d=c&&ux(),e=[9351424];d&&e.push(20969472);return Ny(a,e).then(function(a){var e=a[a.length-1];a=oj(a[0].events).catch(function(a){b.L.error("Failed to persist events Blob.",a)});d&&0<e.events.size?qx(e.events,void 0,b.Np.bind(b)):c&&px("stats.json",e.Ff,void 0,void 0);return a})})};g.Np=function(a){a&&(tx().b=Date.now())};
g.Si=function(a){if(this.o)return ab();this.L.info("Received message to upload logs for "+a);return this.b?Ny(this.b,[20969472]).then(function(b){b=k(b).next().value;return 0==b.events.size?"":qx(b.events,a)}):Promise.resolve(Sy(this,a))};
var Sy=function(a,b){var c=window.localStorage.getItem("mr.temp.mirror.cast.Service.eventsBlob");if(null==c||1>c.length)c=null;else{for(var d=new Uint16Array(c.length),e=0;e<c.length;++e)d[e]=c.charCodeAt(e);c=d.buffer;d=(new Uint8Array(c,c.byteLength-1,1))[0];c=new Uint8Array(c,0,c.byteLength-(0==d?2:1));c=new Blob([c],{type:"application/gzip"})}if(null!=c&&0!=c.size)return oj(new Blob),a.L.info("Uploading saved logs for feedback."),qx(c,b)};g=Qy.prototype;
g.onError=function(a){this.L.info("Mirroring service error: "+a);this.l()};g.didStart=function(){qg(this.G)?this.wg():rg(this.G)?this.tg():tg(this.G)&&this.Ch()};g.didStop=function(){this.l()};g.send=function(a){if(this.j){var b=JSON.parse(a.jsonFormatData);kb(this.L,function(){return"Sending message: "+JSON.stringify(b)});this.j.sendMessage(a.jsonFormatData,{namespace:a.messageNamespace})}};
g.Op=function(a){if(a&&(a.namespace_===mojo.MirroringWebRtcNamespace||a.namespace_===mojo.MirroringRemotingNamespace)&&this.s){var b=new mojo.MirroringCastMessage;b.messageNamespace=a.namespace_;"string"!==typeof a.data?this.L.info("Received non-string as JSON"):(b.jsonFormatData=a.data,this.s.send(b))}};
var Ry=function(a,b){var c=new mojo.MirroringSessionParameters;c.receiverAddress=new mojo.IPAddress;c.receiverAddress.addressBytes=a.ib.Df.split(".").map(function(a){return parseInt(a,10)});c.receiverModelName=a.ib.Qd;c.type=b.shouldCaptureVideo&&b.shouldCaptureAudio?mojo.MirroringSessionType.AUDIO_AND_VIDEO:b.shouldCaptureVideo?mojo.MirroringSessionType.VIDEO_ONLY:mojo.MirroringSessionType.AUDIO_ONLY;return c};Qy.prototype.Rb=function(a,b,c){og(14);this.A&&Cg(this.A,a,b,c)};
Qy.prototype.l=function(){chrome.tabs.onUpdated.removeListener(this.N);return this.o?this.W?this.h?(this.h.ptr.reset(),this.s=this.h=null,this.j&&this.j.Oa(),this.j=null,this.B&&(this.B.close(),this.B=null),this.D&&(this.D.close(),this.D=null),this.H=this.G="",this.ug(),Promise.resolve(!0)):Promise.resolve(!1):Promise.reject("Not initialized"):wg.prototype.l.call(this)};
Qy.prototype.Ui=function(a,b,c,d,e,f){return this.o?Gf(Error("Mirroring service does not support updating stream")):wg.prototype.Ui.call(this,a,b,c,d,e,f)};Qy.prototype.send=Qy.prototype.send;Qy.prototype.didStop=Qy.prototype.didStop;Qy.prototype.didStart=Qy.prototype.didStart;Qy.prototype.onError=Qy.prototype.onError;var Ty=new Qy;kg("mr.mirror.cast.Service",Ty);
